FROM python:3.9-slim AS builder

WORKDIR /code/src/

COPY ./ /code/src

RUN pip install --no-cache-dir -r /code/src/requirements.txt

FROM python:3.9-slim AS production

WORKDIR /code/src/

COPY --from=builder /usr/local/lib/python3.9/site-packages/ /usr/local/lib/python3.9/site-packages/
COPY --from=builder /usr/local/bin/ /usr/local/bin/
COPY --from=builder /code/src /code/src

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]